---
- hosts: router
  tasks:
    - name: Set automatic network configuration
      template: src=interfaces.default dest=/etc/network/interfaces
    - sysctl: name=net.ipv4.ip_forward value=0
    - service: name=isc-dhcp-server enabled=no
    - apt: name=iptables-persistent
    - service: name=iptables-persistent enabled=no
    - service: name=hostapd enabled=no
    - service: name=squid3 enabled=no
